name: Keep Streamlit App Alive

on:
  schedule:
    - cron: '0 0 * * *'   # runs every day at midnight UTC
  workflow_dispatch:          # Allows manual triggering

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Keep alive commit
        run: |
          echo "Last keepalive run: $(date)" > keepalive.txt
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add keepalive.txt
          git commit -m "keepalive commit"
          git push

